

- hosts: workers

  tasks: 

  - name: "Stop Containers"
    shell: docker stop $(docker ps -a -q)
    ignore_errors: true

  - name: "remove all docker containers"
    shell: docker rm $(docker ps -a -q)
    ignore_errors: true

  - name: "remove all docker images"
    shell: docker rmi $(docker images -q)
    ignore_errors: true




