
- hosts: master

  tasks:

  - name: "Run Master"
    supervisorctl:
        name: harmonic_master
        state: started
    become: true

- hosts: workers

  tasks: 

  - name: "Run Worker"
    supervisorctl:
        name: harmonic_worker
        state: started
    become: true
