 
- hosts: master

  tasks:

  - name: "Stop Master"
    supervisorctl:
        name: harmonic_master
        state: stopped
    become: true

- hosts: workers

  tasks: 

  - name: "Stop Workers"
    supervisorctl:
        name: harmonic_worker
        state: stopped
    become: true
