 
- hosts: master

  tasks:

  - name: "Stop Master"
    command: screen -X -S H-Master quit
    become: yes
    ignore_errors: yes

    # Stop any sessions created as non-root by mistake

  - name: "Stop Master"
    command: screen -X -S H-Master quit
    become: no
    ignore_errors: yes

- hosts: workers

  tasks: 

  - name: "Stop Workers"
    command: screen -X -S H-Worker quit
    become: yes
    ignore_errors: yes

    # Stop any sessions created as non-root by mistake

  - name: "Stop Workers (non-root)"
    command: screen -X -S H-Worker quit
    become: no
    ignore_errors: yes

- hosts: master:workers

  tasks:

  - name: "Remove Dead Screens"
    command: screen -wipe
    become: yes
    ignore_errors: yes


